version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - tramproxy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - tramproxy
    command: npm run dev -- --host

networks:
  tramproxy:
    driver: bridge

